// <auto-generated />
namespace Yaaf.Xmpp.MessageArchiveManager.Sql.MySql.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.8.3")]
    public sealed partial class AutomaticMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AutomaticMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201409292216250_AutomaticMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
